name: Build RPM with Docker

on:
  push:
    tags:
      - 'v*' # Run on new tags
  workflow_dispatch: # Allow manual triggering

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy Dockerfile
        run: |
          cp Dockerfile /root/Dockerfile

      - name: Build Docker Image
        run: |
          docker build -t "${{ github.repository }}:rpm-builder" -f /root/Dockerfile .

      - name: Run Docker Container
        id: run-container
        run: |
          docker run --name rpm-builder-container ${{ github.repository }}:rpm-builder
        continue-on-error: false

      - name: Copy RPM Files from Container
        run: |
          mkdir -p output
          docker cp rpm-builder-container:/root/output output/

      - name: Remove Docker Container
        run: |
          docker rm -f rpm-builder-container
        continue-on-error: true

      - name: List Files in Output Directory
        run: |
          ls -l output/

      - name: Upload RPM Files as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-rpms
          path: output/
