name: Build RPM with Docker

on:
  push:
    tags:
      - 'v*' # Run on new tags
  workflow_dispatch: # Allow manual triggering

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access files like the Dockerfile
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build Docker Image directly in the working directory
      - name: Build Docker Image
        run: |
          docker build -t "${{ github.repository }}:rpm-builder" -f ./Dockerfile .

      # Run the Docker Container to build the RPM files
      - name: Run Docker Container
        id: run-container
        run: |
          docker run --name rpm-builder-container ${{ github.repository }}:rpm-builder

      # Copy the RPM files from the container to the host machine
      - name: Copy RPM Files from Container
        run: |
          mkdir -p output
          docker cp rpm-builder-container:/root/output ./output/

      # Remove the Docker Container after copying the RPM files
      - name: Remove Docker Container
        run: |
          docker rm -f rpm-builder-container
        continue-on-error: true # Avoid breaking if the container is already removed

      # List the output directory contents
      - name: List Files in Output Directory
        run: |
          ls -l ./output/

      # Upload the RPM files as artifacts
      - name: Upload RPM Files as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-rpms
          path: ./output/
