name: Build DRBD RPMs

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday
  workflow_dispatch:      # Allow manual triggering
  push:
    tags:
      - 'v*'

jobs:
  build-rpm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: drbd-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build DRBD RPMs
        run: |
          docker run --name builder drbd-builder
      
      - name: Copy Build Artifacts
        run: |
          docker cp builder:${OUTPUT_DIR} ./output
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body_path: ./output/build_report.txt
          files: |
            ./output/RPMS/x86_64/*.rpm
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
      
      - name: Upload Artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v3
        with:
          name: drbd-rpms
          path: |
            ./output/RPMS/x86_64/*.rpm
            ./output/build_report.txt
