name: Build RPM and Publish Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t "${{ github.repository }}:rpm-builder" -f ./Dockerfile .

      # Step 3: Run Docker Container
      - name: Run Docker Container
        id: run-container
        run: |
          docker run --name rpm-builder-container ${{ github.repository }}:rpm-builder

      # Step 4: Copy RPM Files from Container
      - name: Copy RPM Files from Container
        run: |
          mkdir -p output
          docker cp rpm-builder-container:/root/output/RPMS ./output/

      # Step 5: Debug Files on Host
      - name: List Files in Output Directory
        run: |
          ls -lR ./output/

      # Step 6: Remove Docker Container
      - name: Remove Docker Container
        run: |
          docker rm -f rpm-builder-container
        continue-on-error: true

      # Step 7: Upload RPM Files to GitHub Release
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref_name }}.
            This release includes the following RPM files:
          artifacts: |
            ./output/RPMS/x86_64/*.rpm
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
