name: DRBD RPM Build and Release

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even if no new kernel version'
        type: boolean
        default: false
  push:
    paths:
      - 'Dockerfile'
      - 'scripts/**'
      - '.github/workflows/drbd-build.yml'

jobs:
  check-kernel-versions:
    runs-on: ubuntu-latest
    outputs:
      kernel_changed: ${{ steps.check-versions.outputs.kernel_changed }}
      kernel_versions: ${{ steps.check-versions.outputs.kernel_versions }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest kernel versions
        id: check-versions
        run: |
          # Create a temporary container to get kernel versions
          docker build -t kernel-checker --target base .
          CURRENT_VERSIONS=$(docker run --rm kernel-checker /usr/local/bin/get-kernels.sh)
          
          # Get previously built versions
          PREV_VERSIONS=""
          if [ -f ".kernel-versions" ]; then
            PREV_VERSIONS=$(cat .kernel-versions)
          fi
          
          # Compare versions
          if [ "$CURRENT_VERSIONS" != "$PREV_VERSIONS" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "kernel_changed=true" >> $GITHUB_OUTPUT
            echo "kernel_versions=$CURRENT_VERSIONS" >> $GITHUB_OUTPUT
            echo "$CURRENT_VERSIONS" > .kernel-versions
          else
            echo "kernel_changed=false" >> $GITHUB_OUTPUT
            echo "kernel_versions=$CURRENT_VERSIONS" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-kernel-versions
    if: needs.check-kernel-versions.outputs.kernel_changed == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: drbd-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run DRBD build
        run: |
          echo "${{ needs.check-kernel-versions.outputs.kernel_versions }}" > kernel_versions.txt
          docker run --name drbd-builder \
            -v $(pwd)/kernel_versions.txt:/tmp/kernel_versions.txt \
            drbd-builder
          
          mkdir -p output
          docker cp drbd-builder:/root/output/. output/
          docker rm drbd-builder

      - name: Generate build report
        run: |
          {
            echo "# DRBD Kernel Module Build Report"
            echo "## Build Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            echo "## Kernel Versions:"
            echo "${{ needs.check-kernel-versions.outputs.kernel_versions }}" | sed 's/^/- /'
            echo -e "\n## Built Modules:"
            find output/RPMS -type f -name "*.rpm" -exec basename {} \; | sed 's/^/- /'
          } > output/build_report.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Kernel Modules Build $(date +'%Y-%m-%d')"
          tag_name: "build-$(date +'%Y%m%d-%H%M')"
          body_path: output/build_report.md
          files: |
            output/RPMS/x86_64/*.rpm
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: drbd-modules-$(date +'%Y%m%d-%H%M')
          path: |
            output/RPMS/x86_64/*.rpm
            output/build_report.md
          retention-days: 7

      - name: Update kernel versions file
        if: success()
        run: |
          echo "${{ needs.check-kernel-versions.outputs.kernel_versions }}" > .kernel-versions
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .kernel-versions
          git commit -m "Update kernel versions [skip ci]"
          git push

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Build failed: Kernel modules build on ${new Date().toISOString().split('T')[0]}`,
              body: `Build failed for kernel versions:\n${process.env.KERNEL_VERSIONS}\n\nSee workflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            }); 